name: flutter_qr_bonus
description: A clean, feature-rich Flutter QR code scanner with scan window, haptics, persistent history, and copy/share functionality. Supports iOS, Android, and Web platforms.
publish_to: 'none'
version: 1.3.0+4

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  mobile_scanner: ^7.0.1
  share_plus: ^11.1.0
  shared_preferences: ^2.2.2
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.7

flutter:
  uses-material-design: true